### ISSUE TITLE
locked extras are not created when pyproject.toml has no project.optional-dependencies section

### ISSUE THREAD

**Issue by houbie** [pdm-project/pdm-build-locked#13]
**Describe the bug**
`pdm build` generates a dist without the locked dependencies when  pyproject.toml has no project.optional-dependencies section

**To Reproduce**
1. clone https://github.com/pyprojectx/pyprojectx
2. running `pdm build` generates the dist with locked dependencies as expected
3. remove the project.optional-dependencies section from pyproject.toml
4. running `pdm build` now generates the dist without locked dependencies

**Comment by sigma67** [comment]
The most likely cause is an outdated version of the plugin. Please pin version `0.2.2` and report back.

**Comment by houbie** [comment]
I'm facing this issue using "pdm-build-locked==0.2.2"

**Comment by sigma67** [comment]
Please try the following

```toml

[build-system]
requires = ["pdm-backend", "pdm-build-locked==0.2.2"]
build-backend = "pdm.backend"
```
